### ISSUE TITLE
Refactor chemical substance/entity hierarchy

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#631]
(with chemical WG)
Discussions on particular edge cases, e.g. insulin, revealed that some aspects of the overall classification of chemical entities in Biolink is confusing, for example classifying molecular entities as biological entities. Working with the chemical WG we will revise this classification, using both ChEBI and SIO as references. As a part of this we will have broad-overarching classifications that group together chemical entities, drug formulations, proteins and peptides, small molecules etc, and more specific subclasses as required.

Linked issues include:
- [x] Separate drug from chemical substance #398 
- [x] should chemical substance have a taxon? #511 
- [x] Chemical Classes #314 
- [x] PR: chemical WG changes #644

**Comment by nlharris** [comment]
@vdancik is working on this.
@vdancik we have a potential agenda item to discuss this at our next DM call (on March 4)--are you ready for that?

**Comment by sierra-moxon** [comment]
- @vdancik presented progress on the data modeling call on March 4 - continuing discussions with feedback from DM team

**Comment by sierra-moxon** [comment]
closing for now - hierarchy went in with biolink-model 2.0.0 - refactoring as a result can be added as additional more granular cases.   (though as always, please feel free to reopen if I interpreted incorrectly :)).
