### ISSUE TITLE
Review predicates -- granular enough? Enough ways to group like things together?

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#632]
Review predicates in light of fix-it queries
Example: "treats"

Related issues:
- [x] A less specific 'treats' #433
- [x] Provide edge qualifier for logical quantification and define behavior #624
- [x] Look at predicates in example: drug associated with decreased risk of atrial fib #625
- [x] Complete mapping of all predicates #286
- [x] New predicate proposals for Translator Min Predicate Set #55

**Comment by sierra-moxon** [comment]
I reviewed all the subtasks on this issue and #625 was the last outstanding one - it is in #799.
